name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        run: pdflatex data_science_case.tex
        working-directory: ./cheat_sheets
