name: writeapaper
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      DIR: cheat_sheets
      FILES: "algorithms_coding.tex data_science_case.tex data_science_coding.tex"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        run: |
          for FILE in ${{ env.FILES }}; do
            pdflatex "$FILE"
            pdflatex "$FILE"
          done
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/*.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled_pdfs
          path: ./github_artifacts
  deploy:
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
  clean:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: delete
        uses: geekyeggo/delete-artifact@v2
        with:
          name: '*.pdf'
