name: Build LaTeX document
on: [push]
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive

    - name: Compile LaTeX document
      run: pdflatex data_science_case.tex
      working-directory: ./cheat_sheets

